### ISSUE TITLE
While stopped instance on RancherVM WebUI, the instance on WebUI disappeared

### ISSUE THREAD

**Issue by cnzg** [rancher/old-vm#42] opened 2015-05-29 01:50 UTC
The following article on Rancher blog show the web UI of RancherVM, i found there are four action functions for each instance, such as: start/stop/delete/console.

http://rancher.com/introducing-ranchervm-package-and-run-virtual-machines-as-docker-containers/

But the reality is that if you stopped instance, the instance would be disappeared, i have never seen a delete button....

My machine is:
~$ uname -a
Linux zgvm3 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ sudo docker version
Client version: 1.7.0-dev
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 15b4511
OS/Arch (client): linux/amd64
Server version: 1.7.0-dev
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 15b4511
OS/Arch (server): linux/amd64

$ sudo docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>                 <none>              3042a47dd469        18 hours ago        188.3 MB
dockercore/docker      latest              cbf4d194aa88        28 hours ago        1.516 GB
rancher/server         latest              5c9ca324d2a8        13 days ago         506.2 MB
rancher/ranchervm      latest              58b342f56fd6        2 weeks ago         249.4 MB
rancher/vm-rancheros   latest              ea786fa28606        2 weeks ago         303.5 MB
ubuntu                 14.04               07f8e8c5e660        4 weeks ago         188.3 MB

**Comment by sheng-liang** [comment] 2015-05-29 02:08
I cannot reproduce this. Can you describe the exact steps you followed? Can you provide the output of docker ps -a?

**Comment by cnzg** [comment] 2015-05-29 02:48
Hi sheng,

1, I create a instance with RancherVM, and then stop instance, the instance disappeared on Rancher Web UI. I tested several times, the result is same.

2, Perform docker ps -a,  i found the instances created during my test. 
zhaoguang@zgvm3:~$ sudo docker ps -a
CONTAINER ID        IMAGE                                                              COMMAND                CREATED             STATUS                     PORTS                   NAMES
40c7598c12e3        rancher/vm-rancheros                                               "/var/lib/rancher/st   45 seconds ago      Up 44 seconds              0.0.0.0:32773->80/tcp   serene_feynman
7bb40692a35d        rancher/vm-rancheros                                               "/var/lib/rancher/st   5 minutes ago       Exited (0) 2 minutes ago                           ecstatic_rosalind
9d7b749fd4d1        rancher/vm-rancheros                                               "/var/lib/rancher/st   15 hours ago        Exited (0) 15 hours ago                            angry_darwin
f605cb24f643        rancher/vm-rancheros                                               "/var/lib/rancher/st   15 hours ago        Exited (0) 15 hours ago                            gloomy_bartik
8eaed657e8f3        rancher/vm-rancheros                                               "/var/lib/rancher/st   17 hours ago        Exited (0) 17 hours ago                            grave_stallman
a544632606e4        rancher/vm-rancheros                                               "/var/lib/rancher/st   17 hours ago        Exited (0) 17 hours ago                            suspicious_thompson
a62a074726e8        rancher/ranchervm                                                  "/var/lib/rancher/st   17 hours ago        Up 17 hours                0.0.0.0:8080->80/tcp    focused_stallman
03db253ecfc1        3042a47dd469a3336eb17b481ada9220658853e3f849f542e9c42473e950741b   "/bin/sh -c 'apt-key   18 hours ago        Exited (2) 18 hours ago                            jolly_curie

**Comment by sheng-liang** [comment] 2015-05-29 05:09
Docker 1.7 broke my script. Just checked in a fix. Can you try again?

**Comment by cnzg** [comment] 2015-05-29 06:56
Hi, 

With the new RancherVM images, this issue is fixed:)

But now, i found another problem as following pic, the third instance is exited status, but the ip address and port also display on Web UI. and other exited instances not so.
![ranchervm_1](https://cloud.githubusercontent.com/assets/12028743/7877845/9055645c-0612-11e5-8be4-d4d4a0e02d8e.png)

**Comment by cnzg** [comment] 2015-05-29 08:17
I also found other two problems:

1, After i pull the new image of RancherVM, and restart host, the IP address of running instance is unreachable.(the ip of running instances:172.17.0.7 and 172.17.0.6 in my test machine)

zhaoguang@zgvm3:~$ sudo docker ps
CONTAINER ID        IMAGE                  COMMAND                CREATED             STATUS              PORTS                   NAMES
731d85a1ea48        rancher/ranchervm      "/var/lib/rancher/st   About an hour ago   Up About an hour    0.0.0.0:8080->80/tcp    agitated_hodgkin
9f2376d323d3        rancher/vm-ubuntu      "/var/lib/rancher/st   4 hours ago         Up 57 minutes       0.0.0.0:32770->80/tcp   suspicious_wright
8eaed657e8f3        rancher/vm-rancheros   "/var/lib/rancher/st   22 hours ago        Up 51 minutes       0.0.0.0:32771->80/tcp   grave_stallman
zhaoguang@zgvm3:~$
zhaoguang@zgvm3:~$ ifconfig
docker0   Link encap:Ethernet  HWaddr 7a:11:c4:60:7a:9c
          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::1057:6ff:fea0:449b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:942 errors:0 dropped:0 overruns:0 frame:0
          TX packets:979 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:398200 (398.2 KB)  TX bytes:86854 (86.8 KB)

2, The console of instance is a blank screen, my browser is chrome 44 version which support canvas...so with the IP address unreachable issue, i think maybe the instances of rancher/vm-rancheros&vm-ubuntu  not run actually.

**Comment by sheng-liang** [comment] 2015-05-29 15:12
I cannot reproduce any of these problems. I have found docker 1.7 development builds to be unstable. Perhaps you could give docker 1.6.1 a try.

Otherwise perhaps we can get on a remote troubleshooting session.

**Comment by deniseschannon** [comment] 2015-05-29 15:57
The latest stable Docker version is 1.6.2, so that would probably be best to try.

**Comment by cnzg** [comment] 2015-05-29 16:37
@sheng-liang @deniseschannon I will try docker 1.6.2 tomorrow, and after that, i will contnue test Rancher solution with docker 1.7, if these problems could reproduce, i hope we can do a remote troubleshooting, thx:)

**Closed as completed** 2015-06-11 06:09 UTC
